export default {
    arr: [{
        id: '000',
        name: '自定义称号',
        price: 20
    }, {
        id: '000',
        img: 'https://s1.52poke.wiki/wiki/8/8e/%E8%B5%A4%E7%BA%A2_OD_B2W2.png',
        name: '小智',
        price: 10
    }, {
        id: '000',
        name: '小茂',
        img: 'https://s1.52poke.wiki/wiki/1/14/%E9%9D%92%E7%BB%BF_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '竹兰',
        img: 'https://s1.52poke.wiki/wiki/2/2d/%E7%AB%B9%E5%85%B0_OD_BWB2W2.png',
        kong: '已经被MoZi买走了'
    }, {
        id: '000',
        name: '阿渡',
        img: 'https://s1.52poke.wiki/wiki/a/ab/%E9%98%BF%E6%B8%A1_OD_B2W2.png',
        kong: '已经被xiluoo买走了'
    }, {
        id: '000',
        name: '大吾',
        img: 'https://s1.52poke.wiki/wiki/c/c2/%E5%A4%A7%E5%90%BE_OD_B2W2.png',
        kong: '已经被Gou_Xuan买走了'
    }, {
        id: '000',
        name: '深灰市道馆馆主~小刚',
        img: 'https://s1.52poke.wiki/wiki/1/1b/%E5%B0%8F%E5%88%9A_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '华蓝市道馆馆主~小霞',
        img: 'https://s1.52poke.wiki/wiki/7/75/%E5%B0%8F%E9%9C%9E_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '枯叶市道馆馆主~马志士',
        img: 'https://s1.52poke.wiki/wiki/0/0b/%E9%A9%AC%E5%BF%97%E5%A3%AB_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '玉虹市道馆馆主~莉佳',
        img: 'https://s1.52poke.wiki/wiki/c/c4/%E8%8E%89%E4%BD%B3_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '浅红市道馆馆主~阿桔',
        img: 'https://s1.52poke.wiki/wiki/1/18/%E9%98%BF%E6%A1%94_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '金黄市道馆馆主~娜姿',
        img: 'https://s1.52poke.wiki/wiki/d/d8/%E5%A8%9C%E5%A7%BF_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '红莲镇道馆馆主~夏伯',
        img: 'https://s1.52poke.wiki/wiki/a/af/%E5%A4%8F%E4%BC%AF_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '常青市道馆馆主~坂木',
        img: 'https://s1.52poke.wiki/wiki/c/cc/%E5%9D%82%E6%9C%A8_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '桔梗市道馆馆主~阿速',
        img: 'https://s1.52poke.wiki/wiki/1/1c/%E9%98%BF%E9%80%9F_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '桧皮镇道馆馆主~阿笔',
        img: 'https://s1.52poke.wiki/wiki/f/fa/%E9%98%BF%E7%AC%94_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '满金市道馆馆主~小茜',
        img: 'https://s1.52poke.wiki/wiki/f/f8/%E5%B0%8F%E8%8C%9C_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '圆朱市道馆馆主~小松',
        img: 'https://s1.52poke.wiki/wiki/b/bd/%E5%B0%8F%E6%9D%BE_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '湛蓝市道馆馆主~阿四',
        img: 'https://s1.52poke.wiki/wiki/a/aa/%E9%98%BF%E5%9B%9B_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '浅黄市道馆馆主~阿蜜',
        img: 'https://s1.52poke.wiki/wiki/6/6a/%E9%98%BF%E8%9C%9C_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '卡吉镇道馆馆主~柳伯',
        img: 'https://s1.52poke.wiki/wiki/8/8a/%E6%9F%B3%E4%BC%AF_OD_HGSS.png',
        price: 10
    }, {
        id: '000',
        name: '烟墨市道馆馆主~小椿',
        img: 'https://s1.52poke.wiki/wiki/e/ee/%E5%B0%8F%E6%A4%BF_OD_HGSS.png',
        price: 10
    }]
}