export default {
    arr: [{
        id: '000',
        name: '自定义称号',
        price: 25
    }, {
        id: '000',
        name: '小智',
        price: 15
    }, {
        id: '000',
        name: '深灰市道馆馆主~小刚',
        price: 15
    }, {
        id: '000',
        name: '华蓝市道馆馆主~小霞',
        price: 15
    }, {
        id: '000',
        name: '枯叶市道馆馆主~马志士',
        price: 15
    }, {
        id: '000',
        name: '玉虹市道馆馆主~莉佳',
        price: 15
    }, {
        id: '000',
        name: '浅红市道馆馆主~阿桔',
        price: 15
    }, {
        id: '000',
        name: '金黄市道馆馆主~娜姿',
        price: 15
    }, {
        id: '000',
        name: '红莲镇道馆馆主~夏伯',
        price: 15
    }, {
        id: '000',
        name: '常青市道馆馆主~坂木',
        price: 15
    }]
}